### ISSUE TITLE
Feature request: Number of commits behind / ahead

### ISSUE THREAD

**Issue by knubie** [yashx/github-active-forks#1]
First of all *thank you* so much for this extension. It's such a good idea and you really nailed the UI.

One idea I had that could be useful is to display the number of commits ahead or behind a repo is. This kind of gives you an idea of how far the two repos have diverged.

**Comment by yashx** [comment]
Sorry, this will not be possible with the way the extension fetches data.

It makes unauthenticated requests which have a [rate limit of 60 requests per hour](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting).

So when you visit a GitHub page it fetches the [top 100 forks (by stars) of the repository](https://github.com/yashx/github-active-forks/blob/2d3b64d2c2931b51b497f21a16dc306b9a2a28af/src/content-script.js#L49) and based on the options selected re-sort or limit the forks shown on the page. (This allows me to avoid making additional API calls when you change an option)

I am able to get this information in one API call using this [endpoint](https://docs.github.com/en/rest/reference/repos#list-forks)
But to implement the feature you are requesting I would need to use this [endpoint](https://docs.github.com/en/rest/reference/repos#commits) for every fork which is not possible.

P.s Btw thank you for the kind words :)
